apiVersion: v1
kind: ConfigMap
metadata:
  name: evershop-config
  namespace: evershop
data:
  DB_HOST: postgres.evershop.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: evershop
  DB_USER: evershop
  NODE_ENV: production
