apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-api
  namespace: healthcare
  labels:
    app: healthcare-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare-api
  template:
    metadata:
      labels:
        app: healthcare-api
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              until nc -z postgres.healthcare.svc.cluster.local 5432; do
                echo "waiting for postgres..."
                sleep 3
              done
      containers:
        - name: healthcare-api
          image: 406260455716.dkr.ecr.us-east-1.amazonaws.com/healthcare-api:v1.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://healthcare:healthcare_dev_pass@postgres.healthcare.svc.cluster.local:5432/healthcare
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
