apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: evershop
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ibraheemcisse/aws-terraform-platform
    targetRevision: main
    path: k8s/evershop
  destination:
    server: https://kubernetes.default.svc
    namespace: evershop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
