apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: healthcare
type: Opaque
stringData:
  POSTGRES_DB: healthcare
  POSTGRES_USER: healthcare
  POSTGRES_PASSWORD: healthcare_dev_pass
