apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: evershop
type: Opaque
stringData:
  POSTGRES_PASSWORD: evershop_dev_password
  POSTGRES_USER: evershop
  POSTGRES_DB: evershop
