apiVersion: v1
kind: ServiceAccount
metadata:
  name: evershop-sa
  namespace: evershop
  annotations:
    # WAF:Security — IRSA scopes ECR pull permissions to this pod only
    eks.amazonaws.com/role-arn: arn:aws:iam::406260455716:role/evershop-dev-ecr-pull-role
